// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContactManagement.Models;

public partial class Contact
{
    public int Contactid { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Mobileno { get; set; }

    public string Email { get; set; }

    public string Uimage { get; set; }
}